
# Window constants
WINDOW_WIDTH = 1000
WINDOW_HEIGHT = 748

# Player constants
JUMP_HEIGHT = 6
PLAYER_VEL = 5

# floor constants
FLOOR_HEIGHT = 10

# Ladder constants
LADDER_WIDTH = 50
UP = -1
DOWN = 1
RUNG_HEIGHT = 25

# direction constants
DIR_UP = 1
DIR_DOWN = 2
DIR_LEFT = 3
DIR_RIGHT = 4
DIR_NO_MOVE = 6


# portal constants
PORTAL_COLOUR = (175, 127, 90)
PORTAL_WIDTH = 60
PORTAL_HEIGHT = 90

# loot constants
LOOT_INTERVAL = 25
LOOT_FLOAT = 5
LOOT_UNKNOWN = 0
LOOT_COIN_GOLD = 1
LOOT_COIN_SILVER = 2
LOOT_COIN_BRONZE = 3
LOOT_VALUE_GOLD = 10

# key press pause constants
KP_UP    = 0
KP_DOWN  = 1
KP_LEFT  = 2
KP_RIGHT = 3
KP_SPACE = 4
KP_m     = 5
KP_d     = 6
KP_foo   = 7  # getting ready for next key to implement
KP_bar   = 8  # getting ready for next key to implement


# game stats
COLOUR_STATS = (204, 51, 255)

# diagnostics
SHOW_DIAGNOSTICS = True
SHOW_PLAYER_HITBOX = True
SHOW_LOOT_HITBOX = True
SHOW_PROJECTILE_HITBOX = False
SHOW_LADDER_HITBOX = True
COLOUR_DIAGNOSTICS = (255, 127, 64)
COLOUR_LOOT_HITBOX = (0,255,0)
COLOUR_LOOT_PERIMETER = (127,127,255)
COLOUR_PLAYER_HITBOX = (255,0,0)
COLOUR_PLAYER_PERIMETER = (255,0,255)
COLOUR_PROJECTILE_PERIMETER = (64,64,255)
COLOUR_PROJECTILE_HITBOX = (127,0,64)
COLOUR_LADDER_HITBOX = (235,64,200)

