
# Window constants
WINDOW_WIDTH = 1000
WINDOW_HEIGHT = 748

# image object constants
IMAGE_OBJECT_LIFE_HEART = 0
IMAGE_OBJECT_HERO_BULLET = 1

# Character constants
CHARACTER_TYPE_HERO_1 = 1
CHARACTER_TYPE_TUMBLEWEED_1 = 2     # large tumbleweed
CHARACTER_TYPE_TUMBLEWEED_2 = 3     # small tumbleweed
CHARACTER_TYPE_TUMBLEWEED_3 = 4     # Large tumbleweed with spikes
CHARACTER_TYPE_THUG_1 = 6
CHARACTER_TYPE_SKELETON_1 = 7
JUMP_HEIGHT_HERO = 6
JUMP_HEIGHT_TUMBLEWEED_1 = 6
JUMP_HEIGHT_TUMBLEWEED_2 = 3
JUMP_HEIGHT_TUMBLEWEED_3 = 6
JUMP_HEIGHT_THUG = 0
JUMP_HEIGHT_SKELETON = 0

# projectile constants
PROJECTILE_HERO_BULLET = 101

# sound constants
SOUND_TYPE_LOOT_SUCCESS = 1
SOUND_TYPE_LOOT_MISS = 2
SOUND_TYPE_PLAYER_SLIDE = 3

# velocity constants
VELOCITY_HERO = 5
VELOCITY_HERO_BULLET = 8
VELOCITY_TUMBLEWEED_1 = 6
VELOCITY_TUMBLEWEED_2 = 8
VELOCITY_TUMBLEWEED_3 = 6
VELOCITY_THUG = 3
VELOCITY_SKELETON = 4

# difficulty constants
DIFFICULTY_GROUP_1 = 1.21
DIFFICULTY_GROUP_2 = 1.41
DIFFICULTY_GROUP_3 = 1.61

# timer events
TIMER_INTERVAL_ENEMY_SPAWN_CHECK = 500
TIMER_EVENT_ENEMY_SPAWN_CHECK = 1339

# Score constants
SCORE_START_NUM_LIVES = 3
SCORE_START_NUM_BULLETS = 3
SCORE_TUMBLEWEED_1 = -100
SCORE_TUMBLEWEED_2 = -50
SCORE_THUG_1 = -100
SCORE_SKELETON_1 = -200

# floor constants
FLOOR_HEIGHT = 10

# Ladder constants
LADDER_WIDTH = 50
UP = -1
DOWN = 1
RUNG_HEIGHT = 25

# direction constants
DIR_UP = 1
DIR_DOWN = 2
DIR_LEFT = 3
DIR_RIGHT = 4
DIR_NO_MOVE = 6


# portal constants
PORTAL_COLOUR = (175, 127, 90)
PORTAL_WIDTH = 60
PORTAL_HEIGHT = 90

# loot constants
LOOT_INTERVAL = 25
LOOT_FLOAT = 5
LOOT_UNKNOWN = 0
LOOT_COIN_GOLD = 1
LOOT_COIN_SILVER = 2
LOOT_COIN_BRONZE = 3
LOOT_HEART_SMALL = 4
LOOT_HEART_MEDIUM = 5
LOOT_HEART_LARGE = 6
LOOT_BULLET_SMALL = 7
LOOT_VALUE_COIN_GOLD = 10
LOOT_VALUE_COIN_SILVER = 5
LOOT_VALUE_COIN_BRONZE = 1
LOOT_VALUE_HEART_SMALL = 1
LOOT_VALUE_HEART_MEDIUM = 2
LOOT_VALUE_HEART_LARGE = 5
LOOT_VALUE_BULLET_SMALL = 1
# LOOT_CHANCE_OF_COIN_GOLD = 5
# LOOT_CHANCE_OF_COIN_SILVER = 5
# LOOT_CHANCE_OF_COIN_BRONZE = 5
LOOT_CHANCE_OF_HEART_SMALL = 5
LOOT_CHANCE_OF_HEART_MEDIUM = 7
LOOT_CHANCE_OF_HEART_LARGE = 8
LOOT_CHANCE_OF_BULLET_SMALL = 10
# LOOT_CHANCE_OF_COIN_ANY = 100


# key press pause constants
KP_UP    = 0
KP_DOWN  = 1
KP_LEFT  = 2
KP_RIGHT = 3
KP_SPACE = 4
KP_m     = 5
KP_d     = 6
KP_s     = 7
KP_p     = 8
KP_e     = 9
KP_foo   = 10  # getting ready for next key to implement
KP_bar   = 11  # getting ready for next key to implement


# game stats
COLOUR_STATS = (204, 51, 255)
COLOUR_PAUSE = (115, 25, 15)
COLOUR_GAME_OVER = (215, 25, 15)

# diagnostics
DEV_MODE = True
SHOW_DIAGNOSTICS = False
SHOW_PLAYER_HITBOX = False
SHOW_LOOT_HITBOX = False
SHOW_PROJECTILE_HITBOX = False
SHOW_LADDER_HITBOX = False
COLOUR_DIAGNOSTICS = (255, 127, 64)
COLOUR_LOOT_HITBOX = (0,255,0)
COLOUR_LOOT_PERIMETER = (127,127,255)
COLOUR_PLAYER_HITBOX = (255,0,0)
COLOUR_PLAYER_PERIMETER = (255,0,255)
COLOUR_PROJECTILE_PERIMETER = (64,64,255)
COLOUR_PROJECTILE_HITBOX = (127,0,64)
COLOUR_LADDER_HITBOX = (235,64,200)

